version: '2'
services:
    structman_db:
        image: docker.io/sanjaysrikakulam/structman
        restart: unless-stopped
        container_name: StructMAn
        hostname: structman
        ports:
            - 3306
        cap_add:
            - NET_ADMIN
            - NET_RAW
        volumes:
            - ./structman/input_data/:/structman/input_data/:Z
            - ./structman/results/:/structman/results/:Z
            - ./mysql_lib/:/var/lib/mysql/:Z
            - ./mysql_logs/:/var/log/mysql/:Z
        environment:
            MYSQL_STRUCTMAN_USER_NAME: "structman"
            MYSQL_STRUCTMAN_USER_PASSWORD: "structman_rocks"
