version: '2'
services:
    structman_db:
        image: structman-debian
        restart: unless-stopped
        container_name: StructMAn
        hostname: structman
        ports:
            - 3306
        cap_add:
            - NET_ADMIN
            - NET_RAW
        volumes:
            - ./structman/input_data/:/structman/input_data/
            - ./structman/results/:/structman/results/
            - ./structman/custom_conf.d/:/etc/mysql/custom_conf.d/
        environment:
            MYSQL_STRUCTMAN_USER_NAME: "structman"
            MYSQL_STRUCTMAN_USER_PASSWORD: "structman_rocks"
